vjezba8/vjezba8/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import url, include
from vjezba8app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('admin/', admin.site.urls),
    url(r'^register/', views.register, name="register"),
    url(r'^user_login/$', views.user_login, name="user_login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^vjezba8app/', include('vjezba8app.urls', namespace='vjezba8app')),
    url(r'^upis_predmeta/(?P<predmet_id>\d+)/(?P<student_id>\d+)/$', views.upis_predmeta, name="upis_predmeta"),
    url(r'^brisanje_predmeta/(?P<predmet_id>\d+)/(?P<student_id>\d+)/$', views.brisanje_predmeta, name="brisanje_predmeta"),
    url(r'^polaganje_predmeta/(?P<predmet_id>\d+)/(?P<student_id>\d+)/$', views.polaganje_predmeta, name="polaganje_predmeta")
]

vjezba8/vjezba8app/urls.py
from django.conf.urls import url
from vjezba8app import views

app_name = 'vjezba8app'

urlpatterns = [
    url(r'^predmetList/', views.PredmetListView.as_view(), name="predmetList"),
    url(r'^(?P<pk>\d+)/$', views.PredmetDetailView.as_view(), name="detail"),
    url(r'^createPredmet/$', views.PredmetCreateView.as_view(), name="create"),
    url(r'^updatePredmet/(?P<pk>\d+)/$', views.PredmetUpdateView.as_view(), name="update"),
    url(r'^korisnikList/', views.KorisnikListView.as_view(), name="list"),
    url(r'^student/(?P<pk>\d+)/$', views.KorisnikDetailView.as_view(), name="detail"),
]

vjezba8/vjezba8app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse
from django.shortcuts import render

class Korisnik(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=64)
    ROLE_ENUM = (('mentor', 'mentor'), ('student', 'student'))
    role = models.CharField(max_length=50, choices=ROLE_ENUM)
    STATUS_ENUM = (('none', 'none'), ('redovni', 'redovni'), ('izvanredni', 'izvanredni'))
    status = models.CharField(max_length=50, choices=STATUS_ENUM)
    def __str__(self):
        return self.email

class Predmet(models.Model):
    ime = models.CharField(max_length=255)
    kod = models.CharField(max_length=16)
    program = models.TextField()
    bodovi = models.IntegerField()
    sem_redovni = models.IntegerField()
    sem_izvanredni = models.IntegerField()
    IZBORNI_ENUM = (('da', 'da'), ('ne', 'ne'))
    izborni = models.CharField(max_length=50, choices=IZBORNI_ENUM)
    def __str__(self):
        return self.ime

    def get_absolute_url(self):
        return reverse("vjezba8app:detail", kwargs={'pk':self.pk})


class Upisi(models.Model):
    student_id = models.ForeignKey(User, on_delete=models.CASCADE)
    predmet_id = models.ForeignKey(Predmet, on_delete=models.CASCADE)
    status = models.CharField(max_length=64)
    def __str__(self):
        return self.status

vjezba8/vjezba8app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Korisnik

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password')

class KorisnikInfoForm(forms.ModelForm):
    class Meta():
        model = Korisnik
        fields = ('email', 'role', 'status')

vjezba8/vjezba8app/views.py
from django.shortcuts import render, redirect
from vjezba8app.forms import UserForm, KorisnikInfoForm
from django.contrib.auth.hashers import make_password
from .models import Predmet, Korisnik, Upisi
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User

# CLASS BASED VIEWS START HERE

class PredmetListView(ListView):
    context_object_name = "predmeti"
    model = Predmet

class PredmetDetailView(DetailView):
    context_object_name = "predmet_detail"
    model = Predmet
    template_name = 'vjezba8app/predmet_detail.html'

class PredmetCreateView(CreateView):
    fields = ('ime', 'kod', 'program', 'bodovi', 'sem_redovni', 'sem_izvanredni', 'izborni')
    model = Predmet

class PredmetUpdateView(UpdateView):
    fields = ('ime', 'kod', 'program', 'bodovi', 'sem_redovni', 'sem_izvanredni', 'izborni')
    model = Predmet

class KorisnikListView(ListView):
    context_object_name = "korisnici"
    model = Korisnik

def filtriraj(k_id):
    svi_upisi = Upisi.objects.filter(student_id=k_id)
    return svi_upisi

class KorisnikDetailView(DetailView):
    context_object_name = "korisnik_detail"
    model = Korisnik
    template_name = 'vjezba8app/korisnik_detail.html'

    def get_context_data(self, **kwargs):
        context = super(KorisnikDetailView,self).get_context_data(**kwargs)
        context['predmeti'] = Predmet.objects.all()
        k_id = self.object.user.id
        #context['upisi'] = Upisi.objects.filter(student_id=self.object.user.korisnik.id)
        context['upisi'] = filtriraj(k_id)
        print("----------------- ", k_id, " -------------------")
        return context



# CLASS BASED VIEWS END HERE

# sa moodla pocinje tu

def upis_predmeta(request, predmet_id, student_id):
    predmet = Predmet.objects.get(id=predmet_id)
    korisnik = Korisnik.objects.get(id=student_id)
    taj_user = korisnik.user
    Upisi.objects.create(predmet_id=predmet, student_id=taj_user, status="rolled")
    return redirect("index")

def polaganje_predmeta(request, predmet_id, student_id):
    predmet = Predmet.objects.get(id=predmet_id)
    korisnik = Korisnik.objects.get(id=student_id)
    taj_user = korisnik.user
    taj_upis = Upisi.objects.filter(predmet_id=predmet, student_id=taj_user)
    taj_upis.delete()
    Upisi.objects.create(predmet_id=predmet, student_id=taj_user, status="passed")
    return redirect("index")

def brisanje_predmeta(request, predmet_id, student_id):
    predmet = Predmet.objects.get(id=predmet_id)
    korisnik = Korisnik.objects.get(id=student_id)
    taj_user = korisnik.user
    taj_upis = Upisi.objects.filter(predmet_id=predmet, student_id=taj_user, status="rolled")
    taj_upis.delete()
    return redirect("index")

#def upisni_list(request, student_id):
    #return redirect()

# sa moodla zavrsava tu

def index(request):
    return render(request, 'vjezba8app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = KorisnikInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = KorisnikInfoForm()
    return render(request, 'vjezba8app/registration.html',
                {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, "vjezba8app/login.html", {})

vjezba8/templates/vjezba8app/allStudents.html
{% extends "vjezba8app/base.html" %}
{% block body_block %}

    <h1>Studenti</h1>

    <div class="list-group">
      {% for k in korisnici %}
        {% if k.role == "student" %}
          <a href="{% url 'upisni_list' user_id=k.id %}" class="list-group-item">{{k.email}}</a>
        {% endif %}
      {% endfor %}
    </div>

{% endblock %}

vjezba8/templates/vjezba8app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          {% if request.user.is_staff %}
            <li><a class="navbar-link" href="{% url 'vjezba8app:predmetList' %}">Predmeti</a></li>
            <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/createPredmet/">Unesite novi predmet</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
          {% if request.user.is_staff %}
            <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/korisnikList/">Studenti</a></li>
          {% endif %}
          {% if user.is_authenticated %}
            {% if not request.user.is_staff %}
              <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/korisnikList/">Upisni list</a></li>
            {% endif %}
          {% endif %}
          <li><a class="navbar-link" href="{% url 'register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

vjezba8/templates/vjezba8app/index.html
{% extends "vjezba8app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>This is home page</h1>
</div>

{% endblock %}

vjezba8/templates/vjezba8app/login.html
<!DOCTYPE html>
<html>
  <title>Login page</title>
<body>
<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>

</body>
</html>

vjezba8/templates/vjezba8app/registration.html
{% extends 'vjezba8app/base.html' %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/korisnik_detail.html
{% extends "vjezba8app/vjezba8app_base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h2>Upisni list za studenta {{korisnik_detail.email}}</h2>
</div>


{% if request.user.is_staff %}
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h2>Neupisani predmeti: </h2>
      <div class="list-group">
        {% for predmet in predmeti %}
          {% if upisi|length == 0 %}
            <h3 class="list-group-item"><li><button><a href="{% url 'upis_predmeta' predmet_id=predmet.pk student_id=korisnik_detail.pk %}">+</a></button> {{ predmet.ime }}</li></h3>
          {% endif %}
          {% for upis in upisi %}
            {% if upis.student_id.username == korisnik_detail.user.username %}
              {% if upis.predmet_id.ime != predmet.ime %}
                <h3 class="list-group-item"><li><button><a href="{% url 'upis_predmeta' predmet_id=predmet.pk student_id=korisnik_detail.pk %}">+</a></button> {{ predmet.ime }}</li></h3>
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endfor %}
      </div>
    </div>

    <div class="col-xs-6">
      <h2>Upisani predmeti:</h2>
      <div class="list-group">
        {% for upis in upisi %}
          {% if upis.student_id.username == korisnik_detail.user.username and upis.status != "passed" %}
            <h3 class="list-group-item">
              <li>
                <button><a href="{% url 'polaganje_predmeta' predmet_id=upis.predmet_id.pk student_id=korisnik_detail.pk %}">✓</a></button> <button><a href="{% url 'brisanje_predmeta' predmet_id=upis.predmet_id.pk student_id=korisnik_detail.pk %}">X</a></button> {{ upis.predmet_id.ime }}
              </li>
            </h3>
          {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="col-xs-6">
      <h2>Položeni predmeti:</h2>
      <div class="list-group">
        {% for upis in upisi %}
          {% if upis.status == "passed" %}
            <h3 class="list-group-item">
              <li>
                <button>✓</button> {{ upis.predmet_id.ime }}
              </li>
            </h3>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% else %}

<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h2>Neupisani predmeti: </h2>
      <div class="list-group">
        {% for predmet in predmeti %}
          {% if upisi|length == 0 %}
            <h3 class="list-group-item"><li><button><a href="{% url 'upis_predmeta' predmet_id=predmet.pk student_id=korisnik_detail.pk %}">+</a></button> {{ predmet.ime }}</li></h3>
          {% endif %}
          {% for upis in upisi %}
            {% if upis.student_id.username == request.user.username %}
              {% if upis.predmet_id.ime != predmet.ime %}
                <h3 class="list-group-item"><li><button><a href="{% url 'upis_predmeta' predmet_id=predmet.pk student_id=korisnik_detail.pk %}">+</a></button> {{ predmet.ime }}</li></h3>
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endfor %}
      </div>
    </div>

    <div class="col-xs-6">
      <h2>Upisani predmeti:</h2>
      <div class="list-group">
        {% for upis in upisi %}
          {% if upis.student_id.username == request.user.username and upis.status != "passed" %}
            <h3 class="list-group-item">
              <li>
                <button><a href="{% url 'polaganje_predmeta' predmet_id=upis.predmet_id.pk student_id=korisnik_detail.pk %}">✓</a></button> <button><a href="{% url 'brisanje_predmeta' predmet_id=upis.predmet_id.pk student_id=korisnik_detail.pk %}">X</a></button> {{ upis.predmet_id.ime }}
              </li>
            </h3>
          {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="col-xs-6">
      <h2>Položeni predmeti:</h2>
      <div class="list-group">
        {% for upis in upisi %}
          {% if upis.status == "passed" %}
            <h3 class="list-group-item">
              <li>
                <button>✓</button> {{ upis.predmet_id.ime }}
              </li>
            </h3>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endif %}


{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/korisnik_list.html
{% extends "vjezba8app/vjezba8app_base.html" %}
{% block body_block %}

<h1>Svi studenti</h1>
<ol>
  {% if request.user.is_staff %}
    {% for student in korisnici %}
      <h2><li><a href="http://127.0.0.1:8000/vjezba8app/student/{{student.id}}">{{student.email}}</a></li></h2>
    {% endfor %}
  {% else %}
    <h2><li><a href="http://127.0.0.1:8000/vjezba8app/student/{{request.user.korisnik.id}}">{{request.user.korisnik.email}}</a></li></h2>
  {% endif %}
</ol>

{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/predmet_detail.html
{% extends "vjezba8app/vjezba8app_base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Detalji o predmetu:</h1>
  <p>Ime: {{predmet_detail.ime}}</p>
  <p>Kod: {{predmet_detail.kod}}</p>
  <p>Program: {{predmet_detail.program}}</p>
  <p>Seminar redovni: {{predmet_detail.sem_redovni}}</p>
  <p>Seminar izvanredni: {{predmet_detail.sem_izvanredni}}</p>
  <p>Izborni: {{predmet_detail.izborni}}</p>
</div>

<div>
  <p><a class="btn btn-warning" href="{% url 'vjezba8app:update' pk=predmet_detail.pk %}">Promijeni</a></p>
</div>

{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/predmet_form.html
{% extends "vjezba8app/vjezba8app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
    Unesite novi predmet
  {% else %}
    Promijenite predmet
  {% endif %}
</h1>

<form class="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn_primary" value="Submit">
</form>

{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/predmet_list.html
{% extends "vjezba8app/vjezba8app_base.html" %}
{% block body_block %}

<h1>Svi predmeti</h1>
<ol>
  {% for predmet in predmeti %}
    <h2><li><a href="http://127.0.0.1:8000/vjezba8app/{{predmet.id}}">{{predmet.ime}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

vjezba8/vjezba8app/templates/vjezba8app/vjezba8app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          {% if request.user.is_staff %}
            <li><a class="navbar-link" href="{% url 'vjezba8app:predmetList' %}">Predmeti</a></li>
            <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/createPredmet/">Unesite novi predmet</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
          {% if request.user.is_staff %}
            <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/korisnikList/">Studenti</a></li>
          {% endif %}
          {% if user.is_authenticated %}
            {% if not request.user.is_staff %}
              <li><a class="navbar-link" href="http://127.0.0.1:8000/vjezba8app/korisnikList/">Upisni list</a></li>
            {% endif %}
          {% endif %}
          <li><a class="navbar-link" href="{% url 'register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>